FROM python:3.9-buster as build
RUN apt-get -y update && apt-get -y install python3 python3-pip
RUN pip install grpcio grpcio-tools
ADD protos /protos
WORKDIR /protos
RUN ./build.sh

WORKDIR /
ADD grpc-service /app
RUN cp -r /protos/gen-py /app

WORKDIR /app
CMD ["python3","./server.py"]