FROM python:3.9-buster as build
RUN apt-get -y update && apt-get -y install python3 python3-pip
RUN pip install grpcio grpcio-tools flask

WORKDIR /
ADD rest-api /app

WORKDIR /app
CMD ["python3","./blucora_rest_api.py"]