# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluecora_tax_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62luecora_tax_service.proto\x12\x03tax\"]\n\x10TaxRefundRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x15\n\rannual_income\x18\x04 \x01(\x02\"#\n\x11TaxRefundResponse\x12\x0e\n\x06refund\x18\x01 \x01(\x02\x32L\n\x03Tax\x12\x45\n\x12\x43\x61lculateTaxReturn\x12\x15.tax.TaxRefundRequest\x1a\x16.tax.TaxRefundResponse\"\x00\x62\x06proto3')



_TAXREFUNDREQUEST = DESCRIPTOR.message_types_by_name['TaxRefundRequest']
_TAXREFUNDRESPONSE = DESCRIPTOR.message_types_by_name['TaxRefundResponse']
TaxRefundRequest = _reflection.GeneratedProtocolMessageType('TaxRefundRequest', (_message.Message,), {
  'DESCRIPTOR' : _TAXREFUNDREQUEST,
  '__module__' : 'bluecora_tax_service_pb2'
  # @@protoc_insertion_point(class_scope:tax.TaxRefundRequest)
  })
_sym_db.RegisterMessage(TaxRefundRequest)

TaxRefundResponse = _reflection.GeneratedProtocolMessageType('TaxRefundResponse', (_message.Message,), {
  'DESCRIPTOR' : _TAXREFUNDRESPONSE,
  '__module__' : 'bluecora_tax_service_pb2'
  # @@protoc_insertion_point(class_scope:tax.TaxRefundResponse)
  })
_sym_db.RegisterMessage(TaxRefundResponse)

_TAX = DESCRIPTOR.services_by_name['Tax']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAXREFUNDREQUEST._serialized_start=35
  _TAXREFUNDREQUEST._serialized_end=128
  _TAXREFUNDRESPONSE._serialized_start=130
  _TAXREFUNDRESPONSE._serialized_end=165
  _TAX._serialized_start=167
  _TAX._serialized_end=243
# @@protoc_insertion_point(module_scope)
