# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bluecora_tax_service_pb2 as bluecora__tax__service__pb2


class TaxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateTaxReturn = channel.unary_unary(
                '/tax.Tax/CalculateTaxReturn',
                request_serializer=bluecora__tax__service__pb2.TaxRefundRequest.SerializeToString,
                response_deserializer=bluecora__tax__service__pb2.TaxRefundResponse.FromString,
                )


class TaxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateTaxReturn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateTaxReturn': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateTaxReturn,
                    request_deserializer=bluecora__tax__service__pb2.TaxRefundRequest.FromString,
                    response_serializer=bluecora__tax__service__pb2.TaxRefundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tax.Tax', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tax(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateTaxReturn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tax.Tax/CalculateTaxReturn',
            bluecora__tax__service__pb2.TaxRefundRequest.SerializeToString,
            bluecora__tax__service__pb2.TaxRefundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
