name: Build a Docker image and Push it to ACR

on:
  workflow_run:
    workflows: [workflow1]
    types:
      - completed
    branches: 
      - jyotish/**
      - main
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'