name: Build a Docker image and Push it to ACR

on:
  #push:
   # branches: 
    #  - 'main'
    # - 'jyotish/**'
  #pull_request:
   # branches: 
    #  - 'main'
on:
  push:
    branches: [main]
      -
  workflow_run:
    workflows: [workflow1]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy-to-acr:
    name: 'deploy-to-acr'
    runs-on: ubuntu-latest
    env:
      acrname: lab49
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        name: 'Publish Image'
        with:
          login-server: lab49.azurecr.io
          username: lab49
          password: D6km1MA5T9/yPJquDHPFbOx51tYKtjnH

      - run: |
          'Publishing'
          docker build ./BlucoraAPI -f BlucoraAPI/Dockerfile.webapi -t lab49.azurecr.io/webapi:${{ github.sha }}
          docker push lab49.azurecr.io/webapi:${{ github.sha }}
