name: workflow1

on:
  push:
    branches: [ main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test"
          echo ${{ github.event.repository.default_branch }}
          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
         # echo ${{ (GITHUB_REF#refs/heads/) != github.event.repository.default_branch }